### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [EternityX/deadcell-gui#1]
i get this crash when i open the demo
![image](https://github.com/EternityX/DEADCELL-GUI/assets/139636168/c5619632-a62d-4a70-8e97-aa0c436a977f)
![image](https://github.com/EternityX/DEADCELL-GUI/assets/139636168/12cc244d-6b1e-4acc-8f57-5046479248ed)
![image](https://github.com/EternityX/DEADCELL-GUI/assets/139636168/3454b118-d1d7-4d8a-8ba5-78ff169106e2)

**Comment by EternityX** [comment]
Looks like the font isn't being created properly, are you using the correct version of ImGui? 
hash: [c4adc925aa1f32de62e648969a4c4f27349e1f22](https://github.com/ocornut/imgui/tree/c4adc925aa1f32de62e648969a4c4f27349e1f22)

Newer versions of ImGui may have changed since this was written.
